In [12]:
from pathlib import Path

import pandas as pd

from common_funcs.utils import find_project_root

In [13]:
root = find_project_root()

data_dir = root / ".." / "data" / "source" / "mvp-ontology-terms-2023-03"
assert data_dir.exists(), data_dir

data_path = data_dir / "ontology_source_descriptors_for_distance_calc_16MAR2023.csv"
assert data_path.exists(), data_path

In [14]:
source_df = pd.read_csv(data_path)
source_df.info()
source_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70301 entries, 0 to 70300
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   unique_ID                  70301 non-null  object
 1   source_descriptions_clean  70301 non-null  object
 2   Source                     70301 non-null  object
dtypes: object(3)
memory usage: 1.6+ MB

,unique_ID,source_descriptions_clean,Source
0,Safety:1:MONDO_0020460,acquired von willebrands disease,Safety
1,Safety:1:MONDO_0015129,addisons disease,Safety
2,Safety:1:MONDO_0008762,alports syndrome,Safety
3,Safety:1:MONDO_0010520,alports syndrome,Safety
4,Safety:1:MONDO_0018965,alports syndrome,Safety
...,...,...,...
70296,GWAS_Catalog:11:EFO_0006510,zoster infection,GWAS_Catalog
70297,OMIM:1:MONDO_0014936,zttk syndrome,OMIM
70298,Clinvar:1:MONDO_0014936,zttk syndrome,Clinvar
70299,Knockout_models:1:MGI_knockout_9748,zygomatic arch hypoplasia,Knockout_models
70300,Safety:3:EFO_0007380,zygomycosis,Safety

In [15]:
source_df.groupby("Source").count()

                  unique_ID  source_descriptions_clean
Source
Clinvar                7243                       7243
Drug_indications       2195                       2195
GWAS_Catalog          32459                      32459
Knockout_models        9822                       9822
MVP_UKBB_FinnGen       5816                       5816
OMIM                   9054                       9054
Safety                 2859                       2859
pLOF                    853                        853

In [22]:
source_df[["unique_ID", "source_descriptions_clean"]].drop_duplicates()

                                 unique_ID         source_descriptions_clean
0                   Safety:1:MONDO_0020460  acquired von willebrands disease
1                   Safety:1:MONDO_0015129                  addisons disease
2                   Safety:1:MONDO_0008762                  alports syndrome
3                   Safety:1:MONDO_0010520                  alports syndrome
4                   Safety:1:MONDO_0018965                  alports syndrome
...                                    ...                               ...
70296          GWAS_Catalog:11:EFO_0006510                  zoster infection
70297                 OMIM:1:MONDO_0014936                     zttk syndrome
70298              Clinvar:1:MONDO_0014936                     zttk syndrome
70299  Knockout_models:1:MGI_knockout_9748         zygomatic arch hypoplasia
70300                 Safety:3:EFO_0007380                       zygomycosis

[70301 rows x 2 columns]